# Server Port for Eureka Server
server.port=8761

# Application Name as registered in Eureka (can be itself, but usually not needed if standalone)
spring.application.name=EUREKA-SERVER

# Eureka Server specific configurations
# These settings make it a standalone server.
# It doesn't register itself with another Eureka server.
eureka.client.register-with-eureka=false
# It doesn't fetch registry information from another Eureka server.
eureka.client.fetch-registry=false
# Optional: Define the hostname if needed, otherwise it uses machine's hostname
eureka.instance.hostname=localhost

# Optional: To prevent "EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP..."
# in a single-node development setup (use with caution, understand implications for production).
# eureka.server.enable-self-preservation=false
# eureka.server.wait-time-in-ms-when-sync-empty=0