server.port=8085
spring.application.name=payment-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

razorpay.key.id=rzp_test_YnWQmV47HrcMMR
razorpay.key.secret=48C4xwPNfSjBKjUSlqCxMBSr
razorpay.webhook.secret=your_test_webhook_secret_123

sparklix.app.jwtSecret=DefaultDevSecretKeyIsOkayForNowButChangeItLaterPlzThisIs32BytesLong!
spring.cloud.compatibility-verifier.enabled=false
# Logging
logging.level.com.sparklix.paymentservice=DEBUG
logging.level.com.razorpay=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG